name: Build Release

on:
  release:
    types: [ published ] # will be triggered when a release is published

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: yarn install-all
    - run: yarn build
